name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell-actions/setup@v2.7.3
        with:
          ghc-version: 'latest'
          cabal-version: 'latest'
      - uses: education/autograding@v1
